### ISSUE TITLE
Version flag doesn't work in example.lua

### ISSUE THREAD

**Issue by thefosk** [amireh/lua_cliargs#29]
I'm trying to run the `example.lua` file provided in the repo, like: `lua example.lua -v`

But it seems like the parsing for `-v` doesn't work, and the version information are never been displayed.

**Comment by Tieske** [comment]
well, it's worse that;
````
C:\Users\Thijs\Dropbox\Lua projects\lua_cliargs>example.lua -v
cli_example.lua: error: bad number of arguments; 1-4 argument(s) must be specified, not 0; re-run with --help for usage.


C:\Users\Thijs\Dropbox\Lua projects\lua_cliargs>example.lua --help
cli_example.lua: error: bad number of arguments; 1-4 argument(s) must be specified, not 0; re-run with --help for usage.


C:\Users\Thijs\Dropbox\Lua projects\lua_cliargs>
````

apparently the parsing errors out before it gets a chance to display the help information.

**Comment by Tieske** [comment]
sorry for the noise. That was a configuration issue on my machine.

Anyway problem seems to be that the test defines 1 argument (non-optional) and when validating, it fails and hence the error message.
If you provide the required argument (any value) it works as expected;

````
C:\Temp>lua test.lua -v myfile
cli_example.lua: version 1.2.1

C:\Temp>
````

Not sure how to fix this. It is specific to required arguments. 

One way would be to include a flag to 'stop parsing arguments' for each option.

so
```lua
function cli:add_opt(key, desc, default)
````
would be updated to
```lua
function cli:add_opt(key, desc, default, stop)
````

and the "-v" option would be created as;
```lua
  cli:add_flag("-v, --version", "prints the program's version and exits", true)
````
So when it parses the arguments, it stops upon hitting "-v" and returns an incomplete set of parsed arguments. It is then up to the host program to check the "-v" option.

It's ugly because it breaks the promise of completely handling all options and returning only valid sets.

any ideas?

**Comment by amireh** [comment]
Can't we just define a hook that the host could use to preemptively abort parsing of args when either `-v` or `--help` is passed in?

I would place such a hook somewhere like this https://github.com/amireh/lua_cliargs/blob/master/src/cliargs.lua#L357

```lua
function cli:parse(noprint, dump, on)
  -- ...
  -- args have been parsed, but validations not yet run
  if on.parse then
    rc = on.parse(args)
    if rc == "abort" -- or some code, false maybe
      return true
    end
  end

  -- arg validation and rest of logic proceeds
  -- ...
end
```

I like this better than adding more to the options API which is already complicated. Also, this opens up the door for other hooks if we need them in the future.

What do you think?

**Comment by o-lim** [comment]
I created a PR that would fix this issue.  Check out PR #33.

**Comment by Tieske** [comment]
closing this one in favour of #33
